# Generated by Django 4.0.3 on 2022-03-27 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calid', models.CharField(blank=True, max_length=100, null=True)),
                ('corid', models.CharField(blank=True, max_length=100, null=True)),
                ('estacion_id', models.CharField(blank=True, max_length=100, null=True)),
                ('model_name', models.CharField(blank=True, max_length=100, null=True)),
                ('cal_name', models.CharField(blank=True, max_length=100, null=True)),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('forecast_date', models.DateField(blank=True, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('value_date', models.DateField(blank=True, null=True)),
                ('value', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
            ],
        ),
    ]
